apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-alpha
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql/alpha"